### ISSUE TITLE
Can use for WebRTC Videocall

### ISSUE THREAD

**Issue by joshuaalpuerto** [ianlin/react-native-callkit#11]
Hi,

Can I integrate this with WebRTC Video Call?

Something like this?
<img width="193" alt="screen shot 2017-07-04 at 2 18 14 pm" src="https://user-images.githubusercontent.com/7126484/27817446-ae856fb8-60c3-11e7-8d2e-ebc2e170eb70.png">

Cheers!

**Comment by joshuaalpuerto** [comment]
As I search over stackoverflow, process is once the call is accepted redirect to the page where you handle the Video Call. My question now is instead of `<AppName> Audio..` how can i change the text to something above? `<AppName> Video..`?

**Comment by bsiddiqui** [comment]
@joshuaalpuerto did you figure this?

**Comment by bsiddiqui** [comment]
Anyone looking for a solution to this, the 4th argument in `displayIncomingCall` is `hasVideo:boolean`.

```js
// Display incoming video call
RNCallKit.displayIncomingCall(uuid.v4(), 'test@test.com', 'email', true)
```
