### ISSUE TITLE
Using imageName

### ISSUE THREAD

**Issue by bsiddiqui** [ianlin/react-native-callkit#17]
I've tried using the `imageName` property but I can't get it to display on an incoming call.

I've tried using an image name in my react-native bundle as well as an image in Images.xcassets. Would you mind elaborating on how one would add an image to the bundle?

**Comment by ianlin** [comment]
Hi, what I did is make sure the image file (e.g. `my_pic.png`) is in Xcode's `Build Phases` -> `Copy Bundle Resources`, and specify the filename only when setup RNCallkit.

In this case:

```javascript
{
  appName: 'MyApp',
  imageName: 'my_pic',
}
```

Hope it helps!
