### ISSUE TITLE
How to run up the example?

### ISSUE THREAD

**Issue by imakou** [ianlin/react-native-callkit#20]
Hi all,

I'd like to just run up an example first without sip setting.
I've settled down `AppDelegate.m` already.
App has been compiled and build successfully.

My purpose is just to render the incoming UI in current process.
How can I make it?

``` javascript
import React, { Component } from "react";
import { Platform, StyleSheet, Text, View } from "react-native";
import RNCallKit from "react-native-callkit";
import uuid from "uuid";

export default class App extends Component<{}> {
  constructor(props) {
    super(props);
    RNCallKit.setup({ appName: "CALL_KIT" });
  }
  onIncomingCall() {
    // Store the generated uuid somewhere
    // You will need this when calling RNCallKit.endCall()
    let _uuid = uuid.v4();
    RNCallKit.displayIncomingCall(_uuid, "886900000000");
  }
  render() {
    return <View>{this.onIncomingCall()}</View>;
  }
}

```
The result is nothing happen in the simulator.

Thanks for any opinion.

**Comment by ianlin** [comment]
Perhaps adding a button in your view with `onPress()` listener calling to `this.onIncomingCall()`?

**Comment by imakou** [comment]
@ianlin I've tired your suggestion. But the screen is still the same and doesn't switch to the imcoming call which I want.

In the dev tool, I can see my console.log, so I think the method has been called successfully.

Is anything I missing?

```javascript
export default class App extends Component<{}> {
  constructor(props) {
    super(props);
    RNCallKit.setup({ appName: "CALL_KIT" });
  }
  onIncomingCall() {
    // Store the generated uuid somewhere
    // You will need this when calling RNCallKit.endCall()
    let _uuid = uuid.v4();
    console.log("Hello RNCallKit", RNCallKit); // log is here
    RNCallKit.displayIncomingCall(_uuid, "886900000000");
  }
  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity onPress={this.onIncomingCall}>
          <Text>Hello World!</Text>
        </TouchableOpacity>
      </View>
    );
  }
}
```

**Comment by fcaride** [comment]
Callkit doesnt work on the simulator, but im trying doing the same in a phone and i cant make it work neither.

**Comment by aarkalyk** [comment]
Have you solved the issue yet?

**Comment by aarkalyk** [comment]
Turns out the problem was due to missing VOIP background mode in info.plist file.

`
<key>UIBackgroundModes</key>
<array>
    <string>audio</string>
    <string>voip</string>
</array>
`

changing it from capabilities didn't work for some reason.

@ianlin would be nice to add it in READ.ME :)

**Comment by ianlin** [comment]
Thanks, README updated.
