### ISSUE TITLE
How to properly set up.

### ISSUE THREAD

**Issue by mhaagens** [ianlin/react-native-callkit#4]
I've installed and linked the npm package, added the build phases, replaced the code in AppDelegate.m. Should I add the file RNCallKit.h and paste this code inside?;
I'm getting errors for missing context for method declaration, use of undeclared identifier RNCallKit and use of undeclared identifier rncallkit.

```
- (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
  restorationHandler:(void(^)(NSArray * __nullable restorableObjects))restorationHandler
{
  return [RNCallKit application:application
           continueUserActivity:userActivity
             restorationHandler:restorationHandler];
}
```

**Comment by mhaagens** [comment]
Tried again, installed with rnpm, getting;
"RCNCallKit.h" file not found

**Comment by ianlin** [comment]
Hey @mhaagens, can you check your Xcode with following settings:

- **Build Settings** -> **Header Search Path** has `$(SRCROOT)/../node_modules/react-native-callkit/ios/RNCallKit`

**Comment by ianlin** [comment]
Hey @mhaagens did you set up successfully?

**Comment by kklimuk** [comment]
I had the same issue and that solved the problem for me. Thanks!

**Comment by mhaagens** [comment]
Got it working by adding the Header Search Path. Thanks!

**Comment by mhaagens** [comment]
Instead of opening an issue I'll just ask here. Can I use this library to intercept incoming calls, display the caller data and either hang up/answer the call in my app? Would you be able to provide a high level overview of how that would work? I see there's a displayIncomingCall, but no event listener for it?
