### ISSUE TITLE
Hang up on incoming calls

### ISSUE THREAD

**Issue by Praxey** [ianlin/react-native-callkit#61]
Hi,

I'm building a react-native app which utilizes twilio video for webrtc calls. 

I'm attempting to use pushkit and callkit just to permit my app to ring while in the background, and then, after the receiver answers, swap over to the video interface I've built. 

This is all working with this package. Thanks so much for building this great tool!

My problem: I cannot figure out how to have my app signal to callkit to shut the call off, after the call ends in the app.

The video call in the app ends, but the call kit call is still going.

I can manually end the call, but it feels sloppy and redundant.  

I tried for hours to get the "endcall" method working, only to see after the fact, that it is designed for OUTGOING calls. Is there any easy way to do the same for INCOMING calls? I tried the endAllCalls method, but it is not working either. 

Thanks!

**Comment by saikiranoptisol** [comment]
@Praxey  I'm trying to implement the same scenario. once accepts the call,  video call must be done. i have integrated twilio video successfully. now i'm working with reactnative call kit to receive and to make calls. But i cant able to make calls or receive calls. How did you done that Kindly let me know I was struck in this for past a week.
