### ISSUE TITLE
Open call kit when the app is killed

### ISSUE THREAD

**Issue by LFSCamargo** [ianlin/react-native-callkit#67]
I am having a issue when the app is completely killed the callkit does not popup can there's any solution for that?

**Comment by zxcpoiu** [comment]
You may needs to use voip push, and let system awake your app.

**Comment by zxcpoiu** [comment]
https://github.com/ianlin/react-native-voip-push-notification

**Comment by ttruongatl** [comment]
There is a different solution for Android platform. You can refer the source here: https://github.com/twilio/voice-quickstart-android

**Comment by saikiranoptisol** [comment]
@LFSCamargo  have you done this. i have a doubt how another user will receive call. I have followed https://github.com/andrew781026/rn-callkit-with-fcm        example demo. using which i wanted to make calls. but using that demo if i clickon incoming call only my phone will ring. if i click on outgoing call. not sure what is happening. i need to call to other user who uses my app. can you please explain how i can do that. i need to do call and i need to get calls as well
